// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLsbi0dzsHTw9W4yNyk_op5KL7iSEQYk',
    appId: '1:578797379586:web:5d28b3d8532a391591071b',
    messagingSenderId: '578797379586',
    projectId: 'ai-weather-eaccd',
    authDomain: 'ai-weather-eaccd.firebaseapp.com',
    storageBucket: 'ai-weather-eaccd.firebasestorage.app',
    measurementId: 'G-MJ8R3Y3ZWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_thqawWZlwC7IaeFNE8JLipjWOpD9-I',
    appId: '1:578797379586:android:77190472584e323691071b',
    messagingSenderId: '578797379586',
    projectId: 'ai-weather-eaccd',
    storageBucket: 'ai-weather-eaccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNn9KNAhCjR8cDhBC45amypM43H-JBoy8',
    appId: '1:578797379586:ios:dedabb2781d0ccab91071b',
    messagingSenderId: '578797379586',
    projectId: 'ai-weather-eaccd',
    storageBucket: 'ai-weather-eaccd.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNn9KNAhCjR8cDhBC45amypM43H-JBoy8',
    appId: '1:578797379586:ios:dedabb2781d0ccab91071b',
    messagingSenderId: '578797379586',
    projectId: 'ai-weather-eaccd',
    storageBucket: 'ai-weather-eaccd.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLsbi0dzsHTw9W4yNyk_op5KL7iSEQYk',
    appId: '1:578797379586:web:62af3045be5a53ed91071b',
    messagingSenderId: '578797379586',
    projectId: 'ai-weather-eaccd',
    authDomain: 'ai-weather-eaccd.firebaseapp.com',
    storageBucket: 'ai-weather-eaccd.firebasestorage.app',
    measurementId: 'G-N560L1YBEL',
  );
}
